In [31]:
with open('data/grades.csv', 'r') as f:
    file = f.read()

file

'Name,StudyHours,Grade\nDan,10,50\nJoann,11.5,50\nPedro,9,47\nRosie,16,97\nEthan,9.25,49\nVicky,1,3\nFrederic,11.5,53\nJimmie,9,42\nRhonda,8.5,26\nGiovanni,14.5,74\nFrancesca,15.5,82\nRajab,13.75,62\nNaiyana,9,37\nKian,8,15\nJenny,15.5,70\nJakeem,8,27\nHelena,9,36\nIsmat,6,35\nAnila,10,48\nSkye,12,52\nDaniel,12.5,63\nAisha,12,64\nBill,8,\nTed,,\n'

In [32]:
# versione vecchia di "with"
try:
    f = open('data/grades.csv', 'r')
    file = f.read()
finally:
    f.close()

In [33]:
%pip install pandas

Requirement already satisfied: pandas in c:\Users\WilliamRussell\github\Course_ITS-BigData25-27_Anno2\.venv\Lib\site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\WilliamRussell\github\Course_ITS-BigData25-27_Anno2\.venv\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\WilliamRussell\github\Course_ITS-BigData25-27_Anno2\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\WilliamRussell\github\Course_ITS-BigData25-27_Anno2\.venv\Lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in c:\Users\WilliamRussell\github\Course_ITS-BigData25-27_Anno2\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [34]:
import pandas as pd

df_grades = pd.read_csv('data/grades.csv')
df_grades

         Name  StudyHours  Grade
0         Dan       10.00   50.0
1       Joann       11.50   50.0
2       Pedro        9.00   47.0
3       Rosie       16.00   97.0
4       Ethan        9.25   49.0
5       Vicky        1.00    3.0
6    Frederic       11.50   53.0
7      Jimmie        9.00   42.0
8      Rhonda        8.50   26.0
9    Giovanni       14.50   74.0
10  Francesca       15.50   82.0
11      Rajab       13.75   62.0
12    Naiyana        9.00   37.0
13       Kian        8.00   15.0
14      Jenny       15.50   70.0
15     Jakeem        8.00   27.0
16     Helena        9.00   36.0
17      Ismat        6.00   35.0
18      Anila       10.00   48.0
19       Skye       12.00   52.0
20     Daniel       12.50   63.0
21      Aisha       12.00   64.0
22       Bill        8.00    NaN
23        Ted         NaN    NaN

In [35]:
df_grades.head(10)

       Name  StudyHours  Grade
0       Dan       10.00   50.0
1     Joann       11.50   50.0
2     Pedro        9.00   47.0
3     Rosie       16.00   97.0
4     Ethan        9.25   49.0
5     Vicky        1.00    3.0
6  Frederic       11.50   53.0
7    Jimmie        9.00   42.0
8    Rhonda        8.50   26.0
9  Giovanni       14.50   74.0

In [36]:
df_grades.tail(10)

      Name  StudyHours  Grade
14   Jenny        15.5   70.0
15  Jakeem         8.0   27.0
16  Helena         9.0   36.0
17   Ismat         6.0   35.0
18   Anila        10.0   48.0
19    Skye        12.0   52.0
20  Daniel        12.5   63.0
21   Aisha        12.0   64.0
22    Bill         8.0    NaN
23     Ted         NaN    NaN

In [37]:
df_grades.isnull()

     Name  StudyHours  Grade
0   False       False  False
1   False       False  False
2   False       False  False
3   False       False  False
4   False       False  False
5   False       False  False
6   False       False  False
7   False       False  False
8   False       False  False
9   False       False  False
10  False       False  False
11  False       False  False
12  False       False  False
13  False       False  False
14  False       False  False
15  False       False  False
16  False       False  False
17  False       False  False
18  False       False  False
19  False       False  False
20  False       False  False
21  False       False  False
22  False       False   True
23  False        True   True

In [38]:
df_grades[df_grades.isnull().any(axis=1)]

    Name  StudyHours  Grade
22  Bill         8.0    NaN
23   Ted         NaN    NaN

In [39]:
df_grades.info()

<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        24 non-null     str
 1   StudyHours  23 non-null     float64
 2   Grade       22 non-null     float64
dtypes: float64(2), str(1)
memory usage: 708.0 bytes

In [40]:
df_grades['StudyHours'] = df_grades.StudyHours.fillna(df_grades.StudyHours.mean())
df_grades.isnull().any()

Name          False
StudyHours    False
Grade          True
dtype: bool

In [41]:
# remove rows with any null values
df_grades = df_grades.dropna(axis='index')
df_grades

         Name  StudyHours  Grade
0         Dan       10.00   50.0
1       Joann       11.50   50.0
2       Pedro        9.00   47.0
3       Rosie       16.00   97.0
4       Ethan        9.25   49.0
5       Vicky        1.00    3.0
6    Frederic       11.50   53.0
7      Jimmie        9.00   42.0
8      Rhonda        8.50   26.0
9    Giovanni       14.50   74.0
10  Francesca       15.50   82.0
11      Rajab       13.75   62.0
12    Naiyana        9.00   37.0
13       Kian        8.00   15.0
14      Jenny       15.50   70.0
15     Jakeem        8.00   27.0
16     Helena        9.00   36.0
17      Ismat        6.00   35.0
18      Anila       10.00   48.0
19       Skye       12.00   52.0
20     Daniel       12.50   63.0
21      Aisha       12.00   64.0

In [42]:
df_grades.describe()

       StudyHours      Grade
count   22.000000  22.000000
mean    10.522727  49.181818
std      3.487144  21.737912
min      1.000000   3.000000
25%      9.000000  36.250000
50%     10.000000  49.500000
75%     12.375000  62.750000
max     16.000000  97.000000

In [43]:
df_grades[df_grades.StudyHours > df_grades.StudyHours.mean()].Grade.median()

np.float64(63.5)

# Dati Riposo

Dati estratti da smartwatch

In [44]:
with open('data/riposo.csv') as f:
    file_content = f.read()
print(file_content)

Data,Media pun.,Qualità media,Durata media,Esigenza media di sonno,Media ora di andare a dormire,Media tempo di veglia
Set 25 - Ott 1,64,Discreto,6h 13min,8h 18min,9:46 PM,4:42 AM
Set 18-24,60,Discreto,4h 48min,8h 47min,10:47 PM,3:49 AM
Set 11-17,64,Discreto,6h 0min,8h 54min,9:14 PM,3:58 AM
Set 4-10,58,Scarso,4h 55min,8h 39min,10:44 PM,4:10 AM
Ago 28 - Set 3,62,Discreto,5h 51min,8h 50min,9:09 PM,3:47 AM
Ago 21-27,57,Scarso,5h 27min,8h 43min,10:29 PM,4:53 AM
Ago 14-20,63,Discreto,5h 46min,8h 53min,10:00 PM,4:31 AM
Ago 7-13,56,Scarso,5h 21min,8h 33min,11:19 PM,5:02 AM
Lug 31 - Ago 6,61,Discreto,5h 8min,8h 45min,12:16 AM,5:54 AM
Lug 24-30,67,Discreto,6h 7min,8h 22min,12:18 AM,7:04 AM
Lug 17-23,64,Discreto,5h 49min,8h 37min,12:45 AM,7:17 AM
Lug 10-16,63,Discreto,5h 51min,8h 20min,12:32 AM,7:10 AM
Lug 3-9,72,Discreto,6h 30min,8h 23min,11:21 PM,6:29 AM
Giu 26 - Lug 2,63,Discreto,5h 48min,8h 40min,12:58 AM,7:02 AM
Giu 19-25,64,Discreto,5h 50min,8h 33min,11:58 PM,6:22 AM
Giu 12-18,68,Discreto,6h 34min,8h 12min,11:00 PM,6:19 AM
Giu 5-11,60,Discreto,5h 35min,8h 39min,11:44 PM,5:38 AM
Mag 29 - Giu 4,64,Discreto,6h 19min,8h 14min,10:35 PM,5:04 AM
Mag 22-28,79,Discreto,7h 58min,7h 55min,10:47 PM,7:29 AM
Mag 15-21,52,Scarso,5h 42min,8h 31min,10:58 PM,5:49 AM
Mag 8-14,71,Discreto,6h 38min,8h 33min,10:07 PM,5:21 AM
Mag 1-7,66,Discreto,6h 14min,8h 26min,9:45 PM,4:35 AM
Apr 24-30,--,--,--,--,--,--
Apr 17-23,66,Discreto,5h 41min,8h 0min,10:45 PM,4:46 AM
Apr 10-16,64,Discreto,6h 17min,8h 57min,10:37 PM,5:26 AM
Apr 3-9,59,Scarso,5h 26min,8h 46min,11:10 PM,4:50 AM
Mar 27 - Apr 2,56,Scarso,5h 16min,8h 42min,10:39 PM,4:14 AM
Mar 20-26,65,Discreto,5h 46min,8h 40min,10:49 PM,4:56 AM
Mar 13-19,64,Discreto,5h 30min,8h 33min,11:43 PM,5:34 AM
Mar 6-12,70,Discreto,6h 38min,8h 20min,10:02 PM,5:05 AM
Feb 27 - Mar 5,69,Discreto,5h 39min,8h 10min,10:25 PM,4:39 AM
Feb 20-26,76,Discreto,5h 50min,7h 0min,12:10 AM,6:26 AM
Feb 13-19,61,Discreto,5h 54min,8h 0min,11:05 PM,5:39 AM
Feb 6-12,78,Discreto,7h 46min,8h 14min,9:45 PM,6:03 AM
Gen 30 - Feb 5,64,Discreto,6h 53min,8h 29min,9:20 PM,4:48 AM
Gen 23-29,72,Discreto,7h 22min,8h 8min,9:25 PM,5:25 AM
Gen 16-22,56,Scarso,6h 31min,8h 18min,10:32 PM,5:53 AM
Gen 9-15,67,Discreto,5h 49min,8h 40min,9:30 PM,3:55 AM
Gen 2-8,60,Discreto,5h 5min,8h 43min,9:10 PM,2:48 AM
Dic 26, 2024 - Gen 1, 2025,52,Scarso,9h 59min,8h 0min,9:13 PM,8:17 AM
Dic 19-25, 2024,67,Discreto,6h 36min,8h 8min,1:53 AM,9:01 AM
Dic 12-18, 2024,70,Discreto,6h 43min,8h 30min,10:06 PM,5:08 AM
Dic 5-11, 2024,64,Discreto,6h 53min,8h 6min,10:09 PM,5:42 AM
Nov 28 - Dic 4, 2024,65,Discreto,6h 6min,8h 41min,9:53 PM,4:36 AM
Nov 21-27, 2024,64,Discreto,5h 10min,8h 22min,11:11 PM,4:44 AM
Nov 14-20, 2024,64,Discreto,5h 22min,8h 46min,10:34 PM,4:24 AM
Nov 7-13, 2024,68,Discreto,6h 2min,8h 20min,11:47 PM,6:05 AM
Ott 31 - Nov 6, 2024,70,Discreto,6h 36min,8h 19min,10:46 PM,5:45 AM
Ott 24-30, 2024,69,Discreto,7h 13min,8h 15min,10:13 PM,5:54 AM
Ott 17-23, 2024,70,Discreto,7h 4min,8h 45min,9:54 PM,5:29 AM
Ott 10-16, 2024,63,Discreto,6h 21min,8h 44min,10:03 PM,4:45 AM
Ott 3-9, 2024,66,Discreto,6h 38min,8h 34min,9:14 PM,4:32 AM

In [45]:
# opzione diretta per leggere e stampare le righe di un file CSV
with open('data/riposo.csv') as f:
    for line in f:
        print(line)

Data,Media pun.,Qualità media,Durata media,Esigenza media di sonno,Media ora di andare a dormire,Media tempo di veglia

Set 25 - Ott 1,64,Discreto,6h 13min,8h 18min,9:46 PM,4:42 AM

Set 18-24,60,Discreto,4h 48min,8h 47min,10:47 PM,3:49 AM

Set 11-17,64,Discreto,6h 0min,8h 54min,9:14 PM,3:58 AM

Set 4-10,58,Scarso,4h 55min,8h 39min,10:44 PM,4:10 AM

Ago 28 - Set 3,62,Discreto,5h 51min,8h 50min,9:09 PM,3:47 AM

Ago 21-27,57,Scarso,5h 27min,8h 43min,10:29 PM,4:53 AM

Ago 14-20,63,Discreto,5h 46min,8h 53min,10:00 PM,4:31 AM

Ago 7-13,56,Scarso,5h 21min,8h 33min,11:19 PM,5:02 AM

Lug 31 - Ago 6,61,Discreto,5h 8min,8h 45min,12:16 AM,5:54 AM

Lug 24-30,67,Discreto,6h 7min,8h 22min,12:18 AM,7:04 AM

Lug 17-23,64,Discreto,5h 49min,8h 37min,12:45 AM,7:17 AM

Lug 10-16,63,Discreto,5h 51min,8h 20min,12:32 AM,7:10 AM

Lug 3-9,72,Discreto,6h 30min,8h 23min,11:21 PM,6:29 AM

Giu 26 - Lug 2,63,Discreto,5h 48min,8h 40min,12:58 AM,7:02 AM

Giu 19-25,64,Discreto,5h 50min,8h 33min,11:58 PM,6:22 AM

Giu 12-18,68,Discreto,6h 34min,8h 12min,11:00 PM,6:19 AM

Giu 5-11,60,Discreto,5h 35min,8h 39min,11:44 PM,5:38 AM

Mag 29 - Giu 4,64,Discreto,6h 19min,8h 14min,10:35 PM,5:04 AM

Mag 22-28,79,Discreto,7h 58min,7h 55min,10:47 PM,7:29 AM

Mag 15-21,52,Scarso,5h 42min,8h 31min,10:58 PM,5:49 AM

Mag 8-14,71,Discreto,6h 38min,8h 33min,10:07 PM,5:21 AM

Mag 1-7,66,Discreto,6h 14min,8h 26min,9:45 PM,4:35 AM

Apr 24-30,--,--,--,--,--,--

Apr 17-23,66,Discreto,5h 41min,8h 0min,10:45 PM,4:46 AM

Apr 10-16,64,Discreto,6h 17min,8h 57min,10:37 PM,5:26 AM

Apr 3-9,59,Scarso,5h 26min,8h 46min,11:10 PM,4:50 AM

Mar 27 - Apr 2,56,Scarso,5h 16min,8h 42min,10:39 PM,4:14 AM

Mar 20-26,65,Discreto,5h 46min,8h 40min,10:49 PM,4:56 AM

Mar 13-19,64,Discreto,5h 30min,8h 33min,11:43 PM,5:34 AM

Mar 6-12,70,Discreto,6h 38min,8h 20min,10:02 PM,5:05 AM

Feb 27 - Mar 5,69,Discreto,5h 39min,8h 10min,10:25 PM,4:39 AM

Feb 20-26,76,Discreto,5h 50min,7h 0min,12:10 AM,6:26 AM

Feb 13-19,61,Discreto,5h 54min,8h 0min,11:05 PM,5:39 AM

Feb 6-12,78,Discreto,7h 46min,8h 14min,9:45 PM,6:03 AM

Gen 30 - Feb 5,64,Discreto,6h 53min,8h 29min,9:20 PM,4:48 AM

Gen 23-29,72,Discreto,7h 22min,8h 8min,9:25 PM,5:25 AM

Gen 16-22,56,Scarso,6h 31min,8h 18min,10:32 PM,5:53 AM

Gen 9-15,67,Discreto,5h 49min,8h 40min,9:30 PM,3:55 AM

Gen 2-8,60,Discreto,5h 5min,8h 43min,9:10 PM,2:48 AM

Dic 26, 2024 - Gen 1, 2025,52,Scarso,9h 59min,8h 0min,9:13 PM,8:17 AM

Dic 19-25, 2024,67,Discreto,6h 36min,8h 8min,1:53 AM,9:01 AM

Dic 12-18, 2024,70,Discreto,6h 43min,8h 30min,10:06 PM,5:08 AM

Dic 5-11, 2024,64,Discreto,6h 53min,8h 6min,10:09 PM,5:42 AM

Nov 28 - Dic 4, 2024,65,Discreto,6h 6min,8h 41min,9:53 PM,4:36 AM

Nov 21-27, 2024,64,Discreto,5h 10min,8h 22min,11:11 PM,4:44 AM

Nov 14-20, 2024,64,Discreto,5h 22min,8h 46min,10:34 PM,4:24 AM

Nov 7-13, 2024,68,Discreto,6h 2min,8h 20min,11:47 PM,6:05 AM

Ott 31 - Nov 6, 2024,70,Discreto,6h 36min,8h 19min,10:46 PM,5:45 AM

Ott 24-30, 2024,69,Discreto,7h 13min,8h 15min,10:13 PM,5:54 AM

Ott 17-23, 2024,70,Discreto,7h 4min,8h 45min,9:54 PM,5:29 AM

Ott 10-16, 2024,63,Discreto,6h 21min,8h 44min,10:03 PM,4:45 AM

Ott 3-9, 2024,66,Discreto,6h 38min,8h 34min,9:14 PM,4:32 AM

In [46]:
header = []
data = []
for line in file_content.splitlines():
    if not header:
        header = line.split(',')
    else:
        # data.append(line.split(','))
        # non basta inserire i dati, dobbiamo sistemare la colonna della date (attualmente un range)
        line_data = line.split(',')

        # prendo la colonna della data (attualmente un range) e splitto per ottenere i valori di inizio e fine
        date_values = line_data[0].split('-')
        # print(data)

        correct_data = []
        if len(line_data) > len(header): #se il numero di dati nella riga è maggiore del numero di colonne dell'header
            # estraggo l'anno dalla colonna della data (attualmente un range)
            year = line_data[1].split('-')[0]
            correct_data.append(year)
        else:
            correct_data.append(None)

        # aggiungo il valore di "data inzio" al set di dati
        correct_data.append(date_values[0])

        start_index = len(line_data)-len(header)+1 # calcola l'indice di partenza per i dati corretti
        #aggiungo gli altri dati a partire dall'indice calcolato
        correct_data.extend(line_data[start_index:])

        data.append(correct_data) # aggiungo la riga corretta ai dati

header = ['year', 'start_date'] + header[1:]
print(len(header), len(data[0]))

8 8

In [47]:
df_riposo = pd.DataFrame(data, columns=header)
df_riposo

,year,start_date,Media pun.,Qualità media,Durata media,Esigenza media di sonno,Media ora di andare a dormire,Media tempo di veglia
0,NaN,Set 25,64,Discreto,6h 13min,8h 18min,9:46 PM,4:42 AM
1,NaN,Set 18,60,Discreto,4h 48min,8h 47min,10:47 PM,3:49 AM
2,NaN,Set 11,64,Discreto,6h 0min,8h 54min,9:14 PM,3:58 AM
3,NaN,Set 4,58,Scarso,4h 55min,8h 39min,10:44 PM,4:10 AM
4,NaN,Ago 28,62,Discreto,5h 51min,8h 50min,9:09 PM,3:47 AM
5,NaN,Ago 21,57,Scarso,5h 27min,8h 43min,10:29 PM,4:53 AM
6,NaN,Ago 14,63,Discreto,5h 46min,8h 53min,10:00 PM,4:31 AM
7,NaN,Ago 7,56,Scarso,5h 21min,8h 33min,11:19 PM,5:02 AM
8,NaN,Lug 31,61,Discreto,5h 8min,8h 45min,12:16 AM,5:54 AM
9,NaN,Lug 24,67,Discreto,6h 7min,8h 22min,12:18 AM,7:04 AM
10,NaN,Lug 17,64,Discreto,5h 49min,8h 37min,12:45 AM,7:17 AM
11,NaN,Lug 10,63,Discreto,5h 51min,8h 20min,12:32 AM,7:10 AM
12,NaN,Lug 3,72,Discreto,6h 30min,8h 23min,11:21 PM,6:29 AM
13,NaN,Giu 26,63,Discreto,5h 48min,8h 40min,12:58 AM,7:02 AM
14,NaN,Giu 19,64,Discreto,5h 50min,8h 33min,11:58 PM,6:22 AM
15,NaN,Giu 12,68,Discreto,6h 34min,8h 12min,11:00 PM,6:19 AM
16,NaN,Giu 5,60,Discreto,5h 35min,8h 39min,11:44 PM,5:38 AM
17,NaN,Mag 29,64,Discreto,6h 19min,8h 14min,10:35 PM,5:04 AM
18,NaN,Mag 22,79,Discreto,7h 58min,7h 55min,10:47 PM,7:29 AM
19,NaN,Mag 15,52,Scarso,5h 42min,8h 31min,10:58 PM,5:49 AM
20,NaN,Mag 8,71,Discreto,6h 38min,8h 33min,10:07 PM,5:21 AM
21,NaN,Mag 1,66,Discreto,6h 14min,8h 26min,9:45 PM,4:35 AM
22,NaN,Apr 24,--,--,--,--,--,--
23,NaN,Apr 17,66,Discreto,5h 41min,8h 0min,10:45 PM,4:46 AM
24,NaN,Apr 10,64,Discreto,6h 17min,8h 57min,10:37 PM,5:26 AM
25,NaN,Apr 3,59,Scarso,5h 26min,8h 46min,11:10 PM,4:50 AM
26,NaN,Mar 27,56,Scarso,5h 16min,8h 42min,10:39 PM,4:14 AM
27,NaN,Mar 20,65,Discreto,5h 46min,8h 40min,10:49 PM,4:56 AM
28,NaN,Mar 13,64,Discreto,5h 30min,8h 33min,11:43 PM,5:34 AM
29,NaN,Mar 6,70,Discreto,6h 38min,8h 20min,10:02 PM,5:05 AM
30,NaN,Feb 27,69,Discreto,5h 39min,8h 10min,10:25 PM,4:39 AM
31,NaN,Feb 20,76,Discreto,5h 50min,7h 0min,12:10 AM,6:26 AM
32,NaN,Feb 13,61,Discreto,5h 54min,8h 0min,11:05 PM,5:39 AM
33,NaN,Feb 6,78,Discreto,7h 46min,8h 14min,9:45 PM,6:03 AM
34,NaN,Gen 30,64,Discreto,6h 53min,8h 29min,9:20 PM,4:48 AM
35,NaN,Gen 23,72,Discreto,7h 22min,8h 8min,9:25 PM,5:25 AM
36,NaN,Gen 16,56,Scarso,6h 31min,8h 18min,10:32 PM,5:53 AM
37,NaN,Gen 9,67,Discreto,5h 49min,8h 40min,9:30 PM,3:55 AM
38,NaN,Gen 2,60,Discreto,5h 5min,8h 43min,9:10 PM,2:48 AM
39,2024,Dic 26,52,Scarso,9h 59min,8h 0min,9:13 PM,8:17 AM
40,2024,Dic 19,67,Discreto,6h 36min,8h 8min,1:53 AM,9:01 AM
41,2024,Dic 12,70,Discreto,6h 43min,8h 30min,10:06 PM,5:08 AM
42,2024,Dic 5,64,Discreto,6h 53min,8h 6min,10:09 PM,5:42 AM
43,2024,Nov 28,65,Discreto,6h 6min,8h 41min,9:53 PM,4:36 AM
44,2024,Nov 21,64,Discreto,5h 10min,8h 22min,11:11 PM,4:44 AM
45,2024,Nov 14,64,Discreto,5h 22min,8h 46min,10:34 PM,4:24 AM
46,2024,Nov 7,68,Discreto,6h 2min,8h 20min,11:47 PM,6:05 AM
47,2024,Ott 31,70,Discreto,6h 36min,8h 19min,10:46 PM,5:45 AM
48,2024,Ott 24,69,Discreto,7h 13min,8h 15min,10:13 PM,5:54 AM
49,2024,Ott 17,70,Discreto,7h 4min,8h 45min,9:54 PM,5:29 AM
50,2024,Ott 10,63,Discreto,6h 21min,8h 44min,10:03 PM,4:45 AM
51,2024,Ott 3,66,Discreto,6h 38min,8h 34min,9:14 PM,4:32 AM

In [48]:
df_riposo.info()

<class 'pandas.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   year                           13 non-null     str
 1   start_date                     52 non-null     str
 2   Media pun.                     52 non-null     str
 3   Qualità media                  52 non-null     str
 4   Durata media                   52 non-null     str
 5   Esigenza media di sonno        52 non-null     str
 6   Media ora di andare a dormire  52 non-null     str
 7   Media tempo di veglia          52 non-null     str
dtypes: str(8)
memory usage: 3.4 KB

In [49]:
# non posso usare questa per convertire in int, perché i NaN causerebbero un errore
# df_riposo['year'] = df_riposo['year'].astype(int)

In [ ]:
year_fill = int(df_riposo['year'].max())+1
year_fill

2025

In [ ]:
#alternativa con errors='coerce' per convertire in int ignorando i NaN
year_fill_alt = pd.to_numeric(df_riposo['year'], errors='coerce').max()
year_fill_alt

np.int64(2025)

In [51]:
df_riposo['year'] = df_riposo['year'].fillna(year_fill).astype(int)
df_riposo.info()

<class 'pandas.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   year                           52 non-null     int64
 1   start_date                     52 non-null     str
 2   Media pun.                     52 non-null     str
 3   Qualità media                  52 non-null     str
 4   Durata media                   52 non-null     str
 5   Esigenza media di sonno        52 non-null     str
 6   Media ora di andare a dormire  52 non-null     str
 7   Media tempo di veglia          52 non-null     str
dtypes: int64(1), str(7)
memory usage: 3.4 KB

In [54]:
dates = df_riposo['start_date'].str.split()
# converto il primo elemento da abbreviazione di mese a numero
mesi = ('Gen', 'Feb', 'Mar', 'Apr', 'Mag', 'Giu', 'Lug', 'Ago', 'Set', 'Ott', 'Nov', 'Dic')

nuove_date = []
for year, date in zip(df_riposo['year'], dates):
    mese_num = mesi.index(date[0]) + 1 # converto l'abbreviazione del mese in numero (+1 rispetto all'indice)
    nuove_date.append(f"{year}-{mese_num:02d}-{date[1]}") #formato YYYY-MM-DD

df_riposo['start_date'] = nuove_date
df_riposo.drop(columns=['year'], inplace=True)

In [57]:
df_riposo.to_csv('data/df_riposo.csv', index=False)
df_riposo.info()

<class 'pandas.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 7 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   start_date                     52 non-null     str
 1   Media pun.                     52 non-null     str
 2   Qualità media                  52 non-null     str
 3   Durata media                   52 non-null     str
 4   Esigenza media di sonno        52 non-null     str
 5   Media ora di andare a dormire  52 non-null     str
 6   Media tempo di veglia          52 non-null     str
dtypes: str(7)
memory usage: 3.0 KB

In [58]:
df_riposo = pd.read_csv('data/df_riposo.csv')
df_riposo.info()

<class 'pandas.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 7 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   start_date                     52 non-null     str
 1   Media pun.                     52 non-null     str
 2   Qualità media                  52 non-null     str
 3   Durata media                   52 non-null     str
 4   Esigenza media di sonno        52 non-null     str
 5   Media ora di andare a dormire  52 non-null     str
 6   Media tempo di veglia          52 non-null     str
dtypes: str(7)
memory usage: 3.0 KB